// Code generated by protoc-gen-go. DO NOT EDIT.
// source: productpage.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c132b88cb2b93e5, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Description struct {
	Rating               int64    `protobuf:"varint,1,opt,name=rating,proto3" json:"rating,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Review               string   `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
	Genre                string   `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Description) Reset()         { *m = Description{} }
func (m *Description) String() string { return proto.CompactTextString(m) }
func (*Description) ProtoMessage()    {}
func (*Description) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c132b88cb2b93e5, []int{1}
}

func (m *Description) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Description.Unmarshal(m, b)
}
func (m *Description) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Description.Marshal(b, m, deterministic)
}
func (m *Description) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Description.Merge(m, src)
}
func (m *Description) XXX_Size() int {
	return xxx_messageInfo_Description.Size(m)
}
func (m *Description) XXX_DiscardUnknown() {
	xxx_messageInfo_Description.DiscardUnknown(m)
}

var xxx_messageInfo_Description proto.InternalMessageInfo

func (m *Description) GetRating() int64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Description) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Description) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

func (m *Description) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "pb.Book")
	proto.RegisterType((*Description)(nil), "pb.Description")
}

func init() { proto.RegisterFile("productpage.proto", fileDescriptor_9c132b88cb2b93e5) }

var fileDescriptor_9c132b88cb2b93e5 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0xaa, 0xc2, 0x30,
	0x10, 0x85, 0x6f, 0x7f, 0x6e, 0xd5, 0x71, 0x21, 0x06, 0x91, 0xd0, 0x95, 0x74, 0x21, 0xae, 0xba,
	0xd0, 0xad, 0x2b, 0xf1, 0x01, 0x4a, 0x7d, 0x82, 0xb4, 0x0e, 0x21, 0x88, 0x49, 0x18, 0x63, 0x7d,
	0x7d, 0xc9, 0xb4, 0x0b, 0x77, 0xf3, 0x1d, 0x0e, 0x87, 0x6f, 0x60, 0xed, 0xc9, 0xdd, 0xdf, 0x7d,
	0xf0, 0x4a, 0x63, 0xed, 0xc9, 0x05, 0x27, 0x52, 0xdf, 0x55, 0x25, 0xe4, 0x17, 0xe7, 0x1e, 0x42,
	0x40, 0x6e, 0xd5, 0x13, 0x65, 0xb2, 0x4b, 0x0e, 0x8b, 0x96, 0xef, 0xca, 0xc0, 0xf2, 0x8a, 0xaf,
	0x9e, 0x8c, 0x0f, 0xc6, 0x59, 0xb1, 0x85, 0x82, 0x54, 0x30, 0x56, 0x73, 0x29, 0x6b, 0x27, 0x12,
	0x1b, 0xf8, 0xf7, 0x64, 0x7a, 0x94, 0x29, 0xc7, 0x23, 0x70, 0x1b, 0x07, 0x83, 0x1f, 0x99, 0xf1,
	0xe4, 0x44, 0xb1, 0xad, 0xd1, 0x12, 0xca, 0x9c, 0xe3, 0x11, 0x8e, 0x67, 0x10, 0xcd, 0xe8, 0xd7,
	0x28, 0x8d, 0x37, 0xa4, 0x21, 0x6e, 0xec, 0x61, 0x36, 0x59, 0x8b, 0x79, 0xed, 0xbb, 0x3a, 0x9a,
	0x96, 0xab, 0x78, 0xfd, 0x78, 0x55, 0x7f, 0x5d, 0xc1, 0xff, 0x9c, 0xbe, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x4f, 0x49, 0x11, 0x84, 0xe4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductPageServiceClient is the client API for ProductPageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductPageServiceClient interface {
	Product(ctx context.Context, in *Book, opts ...grpc.CallOption) (*Description, error)
}

type productPageServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductPageServiceClient(cc *grpc.ClientConn) ProductPageServiceClient {
	return &productPageServiceClient{cc}
}

func (c *productPageServiceClient) Product(ctx context.Context, in *Book, opts ...grpc.CallOption) (*Description, error) {
	out := new(Description)
	err := c.cc.Invoke(ctx, "/pb.ProductPageService/product", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductPageServiceServer is the server API for ProductPageService service.
type ProductPageServiceServer interface {
	Product(context.Context, *Book) (*Description, error)
}

// UnimplementedProductPageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductPageServiceServer struct {
}

func (*UnimplementedProductPageServiceServer) Product(ctx context.Context, req *Book) (*Description, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Product not implemented")
}

func RegisterProductPageServiceServer(s *grpc.Server, srv ProductPageServiceServer) {
	s.RegisterService(&_ProductPageService_serviceDesc, srv)
}

func _ProductPageService_Product_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Book)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductPageServiceServer).Product(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ProductPageService/Product",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductPageServiceServer).Product(ctx, req.(*Book))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductPageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ProductPageService",
	HandlerType: (*ProductPageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "product",
			Handler:    _ProductPageService_Product_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "productpage.proto",
}
